### ISSUE TITLE
Refine dependency for `flowpack/behat`/`neos/behat`

### ISSUE THREAD

**Issue by ComiR** [neos/neos-development-distribution#38]
https://github.com/neos/neos-development-distribution/blob/06efbf84f54211859cd152301054a80a9435d2e7/composer.json#L34
breaks branches < neos 3.0. probably should be replaced f.e. by `flowpack/behat@2.3.x-dev` in 2.3 branch.

**Comment by kdambekalns** [comment]
This has been fixed in the meantime…
